# Generated by Django 5.2.10 on 2026-01-31 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер счёта')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен')], default='draft', max_length=20, verbose_name='Статус')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Дата выставления')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='PDF-файл')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-issue_date'],
            },
        ),
    ]
