# Generated by Django 5.2.10 on 2026-02-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Личный ID чата клиента в Telegram (начинается с минуса для групп или просто число для личных чатов)', max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
