# Generated by Django 5.2.10 on 2026-02-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Личный ID чата клиента в Telegram', max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
